import type { NextPage } from "next";
import Head from "next/head";
import { Content, Header } from "~/components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Notetaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Content />
      </main>
    </>
  );
};

export default Home;
